// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'run the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSuE7691X900qmi0hB6W7_AgfjGEKbvbY',
    appId: '1:1068973622482:android:a08bb5a171b25e8429d90b',
    messagingSenderId: '1068973622482',
    projectId: 'face-attendance-demo-3d793',
    authDomain: 'face-attendance-demo-3d793.firebaseapp.com',
    storageBucket: 'face-attendance-demo-3d793.firebasestorage.app',
    measurementId: 'G-XXXXXXX', // isi kalau ada
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSuE7691X900qmi0hB6W7_AgfjGEKbvbY',
    appId: '1:1068973622482:android:a08bb5a171b25e8429d90b',
    messagingSenderId: '1068973622482',
    projectId: 'face-attendance-demo-3d793',
    storageBucket: 'face-attendance-demo-3d793.firebasestorage.app',
  );
}
